name: Test Compression
on:
  push:
  workflow_dispatch:
env:
  SAVE_CACHE_ON_ANY_FAILURE: 'yes'
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
    - uses: actions/checkout@v2
    - name: NPM install
      run: |
        pwd
        npm install
    - name: Induce error
      id: error-job
      run: exit 1
    - uses: tanuj077/cache@main
      id: cache
      with:
        path: ${{ github.workspace }}/node_modules
        key: hard-code-new12345
        restore-keys: hard-code123
