name: Test Compression
on:
  push:
  schedule:
  - cron: "*/5 * * * *"
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date + '%Y-%m-%dT%H:%M:%S')"
    - uses: actions/checkout@v2
    - uses: actions/github-script@v5
      with:
        script: |
          console.log("process.env['RUNNER_TEMP']="+process.env['RUNNER_TEMP']);
          console.log("process.cwd()="+process.cwd());
          console.log("Home directory = "+require('os').homedir());
    - uses: actions/cache@v3
      id: cache
      with:
        path: ${{ github.workspace }}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ steps.date.outputs.date }} 
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ steps.date.outputs.date }}
