name: Skip save, only restore
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      - name: Get current date
        shell: bash
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - uses: actions/checkout@v2
      - uses: actions/cache/restore@700-actionscache-granular-cache-control
        id: cache-restore
        with:
          path: ${{ github.workspace }}/node_modules
          key: qwertyuiop
          restore-keys: no-
      - name: NPM install
        shell: bash
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          pwd
          npm install
      - name: Get Outputs
        run: | 
            echo "${{ steps.cache-restore.outputs.cache-primary-key }}"
            echo "${{ steps.cache-restore.outputs.cache-restore-key }}"
